name: Update trending subreddits (gummysearch)

on:
  schedule:
    - cron: '15 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-trending-subreddits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run gen_trending_gummy.sh daily
      run: bash scripts/gen_trending_gummy.sh daily > trending-gummy-daily.txt

    - name: Run gen_trending_gummy.sh daily
      run: bash scripts/gen_trending_gummy.sh weekly > trending-gummy-weekly.txt

    - name: Abort if empty
      run: |
        if [ ! -s trending-gummy-daily.txt ] || [ ! -s trending-gummy-weekly.txt ]; then
          echo "One or both files are empty"
          exit 1
        fi

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add trending-gummy-daily.txt trending-gummy-weekly.txt
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "Trending subreddit daily update [$(date +'%Y-%m-%d')]"
          git push
        fi
